### ISSUE TITLE
sixel_ls

### ISSUE THREAD

**Issue by guilafer** [saitoha/PySixel#2]
Hello,
I'm having fun playing with my colorful terminal now that I got mlterm and sixel deployed on my computer.

I see that there is a screenshot showing sixel_ls but I don't see the script anywhere. 
Where can I get sixel_ls?

**Comment by saitoha** [comment]
@guilafer Sorry, I lost complete code.
It was a simple shell script, that calls `qlthumb`, `sixelconv -c -w <width> -e <height>`, `file` and `ls` command utility. `qlthumb` source is [here](https://github.com/saitoha/tanasinn/blob/master/tools/thumb/qlthumb.m)(for OSX).
You can develop your own `sixel_ls` using them...

**Comment by guilafer** [comment]
Thanks for prompt answer.
I'll try to contribute back my attempt at making an ls script.
